-- IDENTIFIER__K
CREATE INDEX IDE_IDX01 ON IDENTIFIER__C(NAME);

-- ITEM_TO_OFFERING_RELATIONSH__K
CREATE INDEX ITOR_IDX01 ON ITEM_TO_OFFERING_RELATIONSH__C(ITEM__C);
CREATE INDEX ITOR_IDX02 ON ITEM_TO_OFFERING_RELATIONSH__C(OFFERING__C);

-- OFFERING_TO_PRICE_PLAN__K
CREATE INDEX OTPP_IDX01 ON OFFERING_TO_PRICE_PLAN__C(PRICE_PLAN_ID__C);
CREATE INDEX OTPP_IDX02 ON OFFERING_TO_PRICE_PLAN__C(OFFERING_ID__C);

-- OFFERING_TO_UPGRADE_OFFERIN__K
CREATE INDEX OTUO_IDX01 ON OFFERING_TO_UPGRADE_OFFERIN__C(OFFERING_ID__C);
CREATE INDEX OTUO_IDX02 ON OFFERING_TO_UPGRADE_OFFERIN__C(UPGRADE_OFFERING_ID__C);

-- PARTY__K
CREATE INDEX PARTY_IDX01 ON PARTY__C(MASTER_ID__C);

-- PDLM__ASSEMBLY__K
CREATE INDEX PDA_IDX01 ON PDLM__ASSEMBLY__C(PDLM__ITEM_NUMBER__C);
CREATE INDEX PDA_IDX02 ON PDLM__ASSEMBLY__C(PARENT_ITEM_NUMBER__C);
CREATE INDEX PDA_IDX03 ON PDLM__ASSEMBLY__C(PDLM__ITEM_REVISION__C);

-- PDLM__ITEM__K
CREATE INDEX PI_IDX01 ON PDLM__ITEM__C(NAME);
CREATE INDEX PI_IDX02 ON PDLM__ITEM__C(MASTER_ID__C);
CREATE INDEX PI_IDX03 ON PDLM__ITEM__C(ID, NAME);
CREATE INDEX PI_IDX04 ON PDLM__ITEM__C(PDLM__CATEGORY__C, NAME);

-- PDLM__ITEM_REVISION__K
CREATE INDEX PIR_IDX01 ON PDLM__ITEM_REVISION__C(ITEM_NUMBER__C);
CREATE INDEX PIR_IDX02 ON PDLM__ITEM_REVISION__C(PDLM__LIFECYCLE_PHASE__C, PDLM__RELEASED__C, PDLM__IS_LATEST_RELEASED__C);

-- PRICE_PLAN_TO_ONETIME_CHARG__K
CREATE INDEX PPTOC_IDX01 ON PRICE_PLAN_TO_ONETIME_CHARG__C(ONETIME_CHARGE_ID__C);
CREATE INDEX PPTOC_IDX02 ON PRICE_PLAN_TO_ONETIME_CHARG__C(PRICE_PLAN_ID__C);

-- PRICE_PLAN_TO_PERIODIC_CHAR__K
CREATE INDEX PPTPC_IDX01 ON PRICE_PLAN_TO_PERIODIC_CHAR__C(PERIODIC_CHARGE_ID__C);
CREATE INDEX PPTPC_IDX02 ON PRICE_PLAN_TO_PERIODIC_CHAR__C(PRICE_PLAN_ID__C);

-- PRODUCT_TO_LV_ASSOCIATION__K
CREATE INDEX PTLV_IDX01 ON PRODUCT_TO_LV_ASSOCIATION__C(ITEM__C);
CREATE INDEX PTLV_IDX02 ON PRODUCT_TO_LV_ASSOCIATION__C(RELATED_LV_ELEMENT__C);

-- PRODUCT_TO_PARTY_ASSOCIATIO__K
CREATE INDEX PTP_IDX01 ON PRODUCT_TO_PARTY_ASSOCIATIO__C(RELATED_PROPEL_ITEM__C);
CREATE INDEX PTP_IDX02 ON PRODUCT_TO_PARTY_ASSOCIATIO__C(PARTY_ID__C);

-- RELATED_ITEM_ASSOCIATION__K
CREATE INDEX REL_IDX01 ON RELATED_ITEM_ASSOCIATION__C(ITEM__C);
CREATE INDEX REL_IDX02 ON RELATED_ITEM_ASSOCIATION__C(RELATED_ITEM_NUMBER__C);

