CREATE TABLE SALESFORCE_SYNC 
(
	ID NUMBER(10) DEFAULT ODS_PK_SEQ.NEXTVAL NOT NULL,
	ACTION VARCHAR2(10) NOT NULL,
	OBJECT_ID VARCHAR(20) NOT NULL,
	OBJECT_TYPE VARCHAR2(255) NOT NULL,
	OBJECT_NAME VARCHAR2(255),
	LAST_UPDATED_BY VARCHAR2(255) NOT NULL,
	LAST_UPDATED TIMESTAMP NOT NULL,
	OLD_VALUES CLOB,
	NEW_VALUES CLOB,
	PAYLOAD CLOB,
	SYNC_CREATED TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
	CONSTRAINT ENSURE_OLD_VALUES_JSON CHECK(OLD_VALUES IS JSON),
	CONSTRAINT ENSURE_NEW_VALUES_JSON CHECK(NEW_VALUES IS JSON),
	CONSTRAINT ENSURE_PAYLOAD_JSON CHECK(PAYLOAD IS JSON),
	PRIMARY KEY (ID)
);

CREATE INDEX SALESFORCE_SYNC_IDX1 ON SALESFORCE_SYNC(LAST_UPDATED);
CREATE INDEX SALESFORCE_SYNC_IDX2 ON SALESFORCE_SYNC(SYNC_CREATED);